/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-07-11 15:13:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.tiles.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class nevigator_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/gram/Desktop/FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TogatherProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1561878082826L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"category\" style=\"width: 1140px; height: 50px;\">\r\n");
      out.write("\t<div class=\"nevigatorBtn\">\r\n");
      out.write("\t\t<!-- 전체 카테고리 버튼 -->\r\n");
      out.write("\t\t<button class=\"categoryBtn width200\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-th\" aria-hidden=\"true\"></i> 전체 카테고리\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"categoryMenu\">\r\n");
      out.write("\t\t\t<!-- 테마버튼 -->\r\n");
      out.write("\t\t\t<div class=\"themaBtn\">테마별</div>\r\n");
      out.write("\t\t\t<div class=\"themaMenu\">\r\n");
      out.write("\t\t\t\t<div>전체</div>\r\n");
      out.write("\t\t\t\t<div>자연</div>\r\n");
      out.write("\t\t\t\t<div>문화/관광</div>\r\n");
      out.write("\t\t\t\t<div>레저/스포츠</div>\r\n");
      out.write("\t\t\t\t<div>쇼핑/맛집</div>\r\n");
      out.write("\t\t\t\t<div>기타</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 지역버튼 -->\r\n");
      out.write("\t\t\t<div class=\"regionBtn\">지역별</div>\r\n");
      out.write("\t\t\t<div class=\"regionMenu\">\r\n");
      out.write("\t\t\t\t<div>전체</div>\r\n");
      out.write("\t\t\t\t<div>서울</div>\r\n");
      out.write("\t\t\t\t<div>경기</div>\r\n");
      out.write("\t\t\t\t<div>인천</div>\r\n");
      out.write("\t\t\t\t<div>강원</div>\r\n");
      out.write("\t\t\t\t<div>제주</div>\r\n");
      out.write("\t\t\t\t<div>대전</div>\r\n");
      out.write("\t\t\t\t<div>충북</div>\r\n");
      out.write("\t\t\t\t<div>충남/세종</div>\r\n");
      out.write("\t\t\t\t<div>부산</div>\r\n");
      out.write("\t\t\t\t<div>울산</div>\r\n");
      out.write("\t\t\t\t<div>경남</div>\r\n");
      out.write("\t\t\t\t<div>대구</div>\r\n");
      out.write("\t\t\t\t<div>경북</div>\r\n");
      out.write("\t\t\t\t<div>광주</div>\r\n");
      out.write("\t\t\t\t<div>전남</div>\r\n");
      out.write("\t\t\t\t<div>전북</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 기간버튼 -->\r\n");
      out.write("\t\t\t<div class=\"timeBtn\">기간별</div>\r\n");
      out.write("\t\t\t<div class=\"timeMenu\">\r\n");
      out.write("\t\t\t\t<div>전체</div>\r\n");
      out.write("\t\t\t\t<div>1박2일</div>\r\n");
      out.write("\t\t\t\t<div>2박3일</div>\r\n");
      out.write("\t\t\t\t<div>3박4일</div>\r\n");
      out.write("\t\t\t\t<div>장기</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 베스트 버튼 -->\r\n");
      out.write("\t\t<button class=\"bestBtn width200\">베스트</button>\r\n");
      out.write("\t\t<!-- 관심목록 버튼 -->\r\n");
      out.write("\t\t<button class=\"intBtn width200\">관심목록</button>\r\n");
      out.write("\t\t<div class=\"intMenu\">\r\n");
      out.write("\t\t\t<div>관심작가</div>\r\n");
      out.write("\t\t\t<div>관심테마</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"nevigatorSearch form-inline\">\r\n");
      out.write("\t\t<!-- 검색 조건 -->\r\n");
      out.write("\t\t<select class=\"custom-select\">\r\n");
      out.write("\t\t\t<option value=\"\">전체</option>\r\n");
      out.write("\t\t\t<option value=\"\">제목</option>\r\n");
      out.write("\t\t\t<option value=\"\">여행작가</option>\r\n");
      out.write("\t\t</select>&emsp;&emsp;\r\n");
      out.write("\t\t<!-- 검색창 -->\r\n");
      out.write("\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"search\">\r\n");
      out.write("\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-info searchBtn\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t&emsp;&emsp;\r\n");
      out.write("\t\t<button type=\"button\" class=\"writeBtn btn btn-outline-dark\">\r\n");
      out.write("\t\t\t<i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
