/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-07-11 09:28:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Eval2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"mypageMenu\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mypageButton\">\r\n");
      out.write("\t\t<!-- 여행신청목록 -->\r\n");
      out.write("\t\t<div style=\"width: 150px; height: 120px;\">\r\n");
      out.write("\t\t\t<div class=\"textMenu\">\r\n");
      out.write("\t\t\t\t<span>여행 신청 목록</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"myongoing.do\" class=\"btnMypageSub\" id=\"ongoing\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\">진행중</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"mylasttrip.do\" class=\"btnMypageSub\" id=\"lastTrip\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\">지난여행</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 여행 작가 -->\r\n");
      out.write("\t\t<div style=\"width: 150px; height: 120px;\">\r\n");
      out.write("\t\t\t<div class=\"textMenu\">\r\n");
      out.write("\t\t\t\t<span>여행 작가</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"myupload.do\" class=\"btnMypageSub\" id=\"upload\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\">내가 올린 여행</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"mystorage.do\" class=\"btnMypageSub\" id=\"storage\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\">임시보관함</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 나의 관심 -->\r\n");
      out.write("\t\t<div style=\"width: 150px; height: 150px;\">\r\n");
      out.write("\t\t\t<div class=\"textMenu\">\r\n");
      out.write("\t\t\t\t<span>나의 관심</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"myjjim.do\" class=\"btnMypageSub\" id=\"jjim\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\">찜한 게시물</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"myfavorwriter.do\" class=\"btnMypageSub\" id=\"favorWriter\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\">관심작가</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"myfavortheme.do\" class=\"btnMypageSub\" id=\"favorTheme\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\">관심테마</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 동행자게시판 -->\r\n");
      out.write("\t\t<div style=\"width: 150px; height: 60px;\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"동행자게시판\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\" class=\"btnMypage\" style=\"border: 0px;\" onclick=\"location.href='mycommunity.do'\" id=\"community\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 쪽지함 -->\r\n");
      out.write("\t\t<div style=\"width: 150px; height: 60px;\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"쪽지함\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\" class=\"btnMypage\" style=\"border: 0px;\" onclick=\"location.href='mymessage.do'\" id=\"message\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 나에 대한 평가 -->\r\n");
      out.write("\t\t<div style=\"width: 150px; height: 120px;\">\r\n");
      out.write("\t\t\t<div class=\"textMenu\">\r\n");
      out.write("\t\t\t\t<span style=\"color: black;\">나에 대한 평가</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"myeval1.do\" class=\"btnMypageSub\" id=\"eval1\" onmouseout=\"change2(this)\" onmouseover=\"change1(this)\">동행자 평가</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"myeval2.do\" class=\"btnMypageSub\" id=\"eval2\" style=\"color: black;\">여행작가 평가</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"none\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 블랙리스트 회원탈퇴 -->\r\n");
      out.write("\t\t<div class=\"bottomMy\">\r\n");
      out.write("\t\t\t<div style=\"float: left\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"btnB\" id=\"blackList\">블랙리스트</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"float: right\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"btnB\" id=\"exit\">회원탈퇴</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"width: 12px; height: 725px; border-right: 2px solid gray; float: left; margin-right: 5px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form id=\"myForm\">\r\n");
      out.write("\t\t<div class=\"mypageContent\">\r\n");
      out.write("\t\t\t<div style=\"width: 950px; height: 60px;\">\r\n");
      out.write("\t\t\t\t<span class=\"subMenuText\">여행작가 평가</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"width: 950px; height: 40px; margin-top: 20px; margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t<div style=\"width: 350px; margin-left: 20px; float: left\">\r\n");
      out.write("\t\t\t\t\t<span style=\"font-size: 20pt; font-weight: bold; font-family: 맑은 고딕;\">나의 작가 점수 : ★★★☆☆</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin-bottom: 15px; width: 950px; height: 25px;\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 25px; width: 100px; float: left;\">\r\n");
      out.write("\t\t\t\t\t<span style=\"font-size: 12pt; font-family: 맑은 고딕;\">게시물 : 2</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"width: 120px; height: 35px; float: right;\">\r\n");
      out.write("\t\t\t\t\t<select class=\"custom-select\" style=\"width: 100px; height: 35px; font-size: 11pt; float: right; bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t<option selected>최신순</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">별점순</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"width: 950px;\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\" style=\"font-size: 13px; font-family: 맑은 고딕; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"background-color: lightgray;\">\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">여행시작일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">여행종료일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">동행자인원</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">별점</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">평가상세</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<!-- foreach문 돌려야함 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">1</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"\">걹루굴얼키밝기밝기울기</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>2019.06.29</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>2019.06.30</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>5</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>★★★★☆</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"button\" value=\"조회\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">2</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Jacob</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Thornton</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>@fat</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">3</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>@twitter</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">4</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>@twitter</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">5</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>@twitter</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">6</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>@twitter</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">7</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>@twitter</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">8</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>@twitter</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">9</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>@twitter</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">10</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>@twitter</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"width: 950px; height: 50px; text-align: center;\">\r\n");
      out.write("\t\t\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t\t<nav aria-label=\"Page navigation example\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pagination\" style=\"color: skyblue;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Previous\"> <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Next\"> <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction change1(obj) {\r\n");
      out.write("\t\t\tobj.style.color = 'black';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction change2(obj) {\r\n");
      out.write("\t\t\tobj.style.color = 'white';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
